### ISSUE TITLE
Add includePaths support for easier Sass usage

### ISSUE THREAD

**Issue by pdehaan** [mozilla/tabzilla#74]
We're trying to use this module w/ Sass and it'd be nice if there was `includePaths` support.

See [**node-normalize-scss**](https://github.com/ranjandatta/node-normalize-scss/blob/master/index.js), [**node-bourbon**](https://github.com/lacroixdesign/node-bourbon/blob/master/index.js), and [**node-neat**](https://github.com/lacroixdesign/node-neat/blob/master/index.js).

This way we could do something like `@import "css/tabzilla";` instead of `@import "../../../node_modules/mozilla-tabzilla/css/tabzilla";`.

Although we'd still need to do some build step trickery to convert "css/tabzilla.css" to "css/_tabzilla.scss" to make it easier to use w/ Sass.

---

For reference, here's my current `_vendor.scss` file:

``` scss
@import 'normalize';
@import '../../../../node_modules/mozilla-tabzilla/css/tabzilla';
```

... where I need to have a build script to rename /css/tabzilla.css to /css/_tabzilla.scss.

``` js
gulp.task('tabzilla-sass', function () {
  gulp.src('../../../../node_modules/mozilla-tabzilla/css/tabzilla.css')
    .pipe(rename('_tabzilla.scss'))
    .pipe(gulp.dest('../../../../node_modules/mozilla-tabzilla/css/'));
});
```

**Comment by pdehaan** [comment]
In fact, not sure if it'd be beneficial to convert the CSS to Sass and then compile to CSS during an npm pre-publish script (since we're already using Gulp).

**Comment by pdehaan** [comment]
I have a crude port of a Sass version of Tabzilla at https://github.com/pdehaan/tabzilla/tree/sass if anybody is interested.

---

### package.json:
```json
{
  "name": "tabzilla-sass",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
  },
  "devDependencies": {
    "gulp": "3.9.0",
    "gulp-sass": "2.0.4",
    "mozilla-tabzilla-scss": "pdehaan/tabzilla#sass"
  }
}
```

### gulpfile.js:
```js
var gulp = require('gulp');
var sass = require('gulp-sass');
var tabzilla = require('mozilla-tabzilla-scss');

gulp.task('sass', function () {
  gulp.src('*.scss')
    .pipe(sass({
      includePaths: [tabzilla.includePaths]
    }))
    .pipe(gulp.dest('css'));
});
```

### main.scss:
```scss
@import "tabzilla";
```

---

### css/main.css _(generated via `$ gulp sass`)_:
```css
#tabzilla {
  float: right;
  position: relative; }

#tabzilla a {
  background-image: url("../media/img/tabzilla-static.png");
  background-repeat: no-repeat;
  display: block;
  height: 37px;
  overflow: hidden;
  position: relative;
  text-indent: 120%;
  white-space: nowrap;
  width: 147px;
  z-index: 2; }

@media only screen and (-webkit-min-device-pixel-ratio: 1.3), only screen and (min--moz-device-pixel-ratio: 1.3), only screen and (-o-min-device-pixel-ratio: 1.3/1), only screen and (min-resolution: 125dpi), only screen and (min-resolution: 1.3dppx) {
  #tabzilla a {
    background-image: url("../media/img/tabzilla-static-high-res.png");
    background-size: 147px 37px; } }

#tabzilla:before {
  background-color: transparent;
  content: '';
  display: block;
  height: 26px;
  left: 28px;
  position: absolute;
  top: 0;
  width: 88px;
  z-index: 1; }

html[dir="rtl"] #tabzilla {
  float: left; }
```
